#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $DB_USER_APP WITH PASSWORD '$DB_PASSWORD_APP';
    CREATE USER $DB_USER_ADMIN WITH PASSWORD '$DB_PASSWORD_ADMIN';

    GRANT ALL PRIVILEGES ON DATABASE tycho TO $DB_USER_ADMIN;
    GRANT ALL ON SCHEMA public TO $DB_USER_ADMIN;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $DB_USER_ADMIN;

    GRANT CONNECT ON DATABASE tycho TO $DB_USER_APP;
    GRANT USAGE ON SCHEMA public TO $DB_USER_APP;
    ALTER DEFAULT PRIVILEGES FOR ROLE $DB_USER_ADMIN IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $DB_USER_APP;
    ALTER DEFAULT PRIVILEGES FOR ROLE $DB_USER_ADMIN IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO $DB_USER_APP;
EOSQL