#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $DB_USER_APP WITH PASSWORD '$DB_PASSWORD_APP';
    CREATE USER $DB_USER_ADMIN WITH PASSWORD '$DB_PASSWORD_ADMIN';

    GRANT ALL PRIVILEGES ON DATABASE tycho TO $DB_USER_ADMIN;
EOSQL