"""Add bounding box columns

Revision ID: 1cf8ac8ece86
Revises: 4faf1aed025a
Create Date: 2026-05-24 17:42:03.186348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf8ac8ece86'
down_revision: Union[str, Sequence[str], None] = '4faf1aed025a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('bounding_box_left', sa.Double(), nullable=False))
    op.add_column('file', sa.Column('bounding_box_bottom', sa.Double(), nullable=False))
    op.add_column('file', sa.Column('bounding_box_right', sa.Double(), nullable=False))
    op.add_column('file', sa.Column('bounding_box_top', sa.Double(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'bounding_box_top')
    op.drop_column('file', 'bounding_box_right')
    op.drop_column('file', 'bounding_box_bottom')
    op.drop_column('file', 'bounding_box_left')
    # ### end Alembic commands ###
