"""Add band_count to Raster and RasterResponse


Revision ID: 930865cd7759
Revises: da75231d210f
Create Date: 2026-05-31 14:07:28.945747

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "930865cd7759"
down_revision: Union[str, Sequence[str], None] = "da75231d210f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("raster", sa.Column("band_count", sa.Integer(), nullable=True))
    op.execute("UPDATE raster SET band_count = 3")
    op.alter_column("raster", "band_count", nullable=False)


# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raster", "band_count")
    # ### end Alembic commands ###
