"""drop the CRS column, CRS will always be 4326. Original CRS can still be found in original file.

Revision ID: da75231d210f
Revises: a1138ff1dbad
Create Date: 2026-05-29 15:45:51.983298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da75231d210f'
down_revision: Union[str, Sequence[str], None] = 'a1138ff1dbad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raster', 'crs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # nullable would have to be True initially and data would have to be backfilled
    op.add_column('raster', sa.Column('crs', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
