"""Add CRS to file record

Revision ID: ee61ef0101cd
Revises: 1cf8ac8ece86
Create Date: 2026-05-24 18:25:43.894150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee61ef0101cd'
down_revision: Union[str, Sequence[str], None] = '1cf8ac8ece86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('crs', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'crs')
    # ### end Alembic commands ###
